apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  template:
    metadata:
      name: order-pod
      labels:
        app: kims-convenience
        tier: backend
        type: order
    spec:
      containers:
        - name: order-container
          image: anshikam/kims-convenience-order
          env:
            - name: MYSQL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mysql-order-config-map
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-order-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-order-config-map
                  key: mysql-user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-order-pass
                  key: mysql-user-password
            - name: DOCKER_INTERNAL
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: docker-internal-url
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kims-convenience
      tier: backend
      type: order

---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30006
  selector:
    app: kims-convenience
    tier: backend
    type: order
