apiVersion: v1
kind: Secret
metadata:
  name: kc-order-mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=       ## rootpassword
  mysql-user-password: cGFzc3dvcmQ=       ## userpassword