# Grafana & Loki instances shared by all KC microservices.

version: '3.8'
services:
  loki:
    image: grafana/loki:latest
    container_name: kc-loki
    #command: ['-config.file=/etc/loki/local-config.yaml']
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:latest
    container_name: kc-grafana
    ports:
      - "3000:3000"
    depends_on:
      - kc-loki
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password

volumes:
  grafana-data: